### ISSUE TITLE
Malformed Header on AWS S3

### ISSUE THREAD

**Issue by brooke-heaton** [lingoda/behat-screenshot-image-driver-aws-s3#3]
I'm getting the following error when trying to connect to S3 from Travis
```
  Client error: `PUT https://naswatravis.s3.amazonaws.com/2019-08-09_18-38-09-6139/features_naswa_javascript_feature_8.png` resulted in a `400 Bad Request` response:  
  <?xml version="1.0" encoding="UTF-8"?>                                                                                                                               
  <Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header (truncated...)   
```

My `Bex\Behat\ScreenshotExtension` configuration is thus:

```
 Bex\Behat\ScreenshotExtension:
      screenshot_taking_mode: failed_steps
      active_image_drivers: aws_s3
      image_drivers:
        aws_s3:
          bucket: naswatravis
          region: "us-east-1"
          version: latest
          credentials_key: AKIAJN5UH2FMI....... // truncated for public review
          credentials_secret: J/jKvlcpzR4mCzVWiqOn4x+tGgMfD7N16....... // truncated for public review
          timeout: 30 # Optional, number of minutes the screenshot will be available when private
          visibility: public-read # Optional, can be only public-read or private
        local:
          screenshot_directory: "/app/screenshots"
          clear_screenshot_directory: true  # Enable removing all images before each test run. It is false by default.
```

My `composer.json` is thus:

```
    "require-dev": {
        "acquia/blt-require-dev": "^10.0@beta",
        "behat/mink-goutte-driver": "~1.2",
        "bex/behat-screenshot": "^1.2",
        "dmore/behat-chrome-extension": "^1.3",
        "drupal/blackfire": "1.x-dev",
        "drupal/xhprof": "1.x-dev",
        "jcalderonzumba/gastonjs": "~1.0.2",
        "jcalderonzumba/mink-phantomjs-driver": "~0.3.1",
        "lingoda/behat-screenshot-image-driver-aws-s3": "^0.1.4",
        "mikey179/vfsstream": "~1.2",
        "webflo/drupal-core-require-dev": "~8.7.0"
    },
```
